version: '3'

services:
  postgres:
    image: postgres:16
    restart: unless-stopped
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data/
    networks:
      - backend
    expose:
      - 5432
    ports:
      - "5432:5432"
    env_file: .env

  fastapi:
    container_name: fastapi_severyanochka
    build: .
    depends_on:
       - postgres
    restart: unless-stopped
    ports:
      - "8000:8000"
    env_file: .env
    volumes:
      - ./:/app
    networks:
      - backend


volumes:
  postgres_dev_data:

networks:
  backend:
    driver: bridge