version: '3'

services:
  postgres:
    image: postgres:16
    restart: always
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data/
    networks:
      - backend
    expose:
      - 5432
    env_file: .env

  fastapi:
    build: .
    depends_on:
       - postgres
    restart: unless-stopped
    ports:
      - "8000:8000"
    env_file: .env
    networks:
      - backend


volumes:
  postgres_dev_data:

networks:
  backend:
    driver: bridge