[tool.poetry]
name = "fastapiproject"
version = "0.1.0"
description = ""
authors = ["PrinterOMG <PrinterOMG@ya.ru>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "3.11.*"
fastapi = "^0.104.1"
uvicorn = {extras = ["standard"], version = "^0.24.0.post1"}
sqlmodel = {extras = ["asyncio"], version = "^0.0.12"}
asyncpg = "^0.29.0"
alembic = "^1.12.1"
passlib = "^1.7.4"
python-jose = "^3.3.0"
gunicorn = "^21.2.0"
python-multipart = "^0.0.6"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
