"""Update phone key

Revision ID: 087137a3838d
Revises: abf24f857fd8
Create Date: 2024-01-18 09:59:09.913555

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '087137a3838d'
down_revision: Union[str, None] = 'abf24f857fd8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('phone_key', sa.Column('is_used', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('phone_key', sa.Column('verified_at', sa.DateTime(), nullable=True))
    op.add_column('phone_key', sa.Column('used_at', sa.DateTime(), nullable=True))

    op.alter_column('phone_key', 'is_used', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('phone_key', 'used_at')
    op.drop_column('phone_key', 'verified_at')
    op.drop_column('phone_key', 'is_used')
    # ### end Alembic commands ###
