"""Update category

Revision ID: 3886feac0553
Revises: bb8f5564ac8f
Create Date: 2024-04-21 13:30:53.746481

"""

from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = '3886feac0553'
down_revision: Union[str, None] = 'bb8f5564ac8f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('category_parent_id_fkey', 'category', type_='foreignkey')
    op.create_foreign_key(
        None, 'category', 'category', ['parent_id'], ['id'], ondelete='SET NULL'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'category', type_='foreignkey')
    op.create_foreign_key(
        'category_parent_id_fkey', 'category', 'category', ['parent_id'], ['id']
    )
    # ### end Alembic commands ###
