"""Make name and last_name nullable in customer

Revision ID: 4f13916a02e9
Revises: 5ffb7a8eabf7
Create Date: 2023-11-30 15:45:25.987236

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4f13916a02e9'
down_revision: Union[str, None] = '5ffb7a8eabf7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('customer', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('customer', 'last_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('customer', 'last_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('customer', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
